# Generated by Django 5.2.4 on 2025-07-22 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_groups_user_is_superuser_user_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('weiblich', 'Weiblich'), ('männlich', 'Männlich'), ('divers', 'Divers')], default='weiblich', max_length=20)),
                ('patient_focus', models.CharField(choices=[('erwachsene', 'Erwachsene (PP)'), ('kinder', 'Kinder und Jugendliche (KJP)')], default='erwachsene', max_length=20)),
                ('therapy_focus', models.CharField(choices=[('ap', 'Psychoanalyse (AP)'), ('st', 'Systemische Therapie (ST)'), ('tp', 'Tiefenpsychologie (TP)'), ('vt', 'Verhaltenstherapie (VT)')], default='vt', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Settings',
                'verbose_name_plural': 'User Settings',
            },
        ),
    ]
