# Generated by Django 5.2.4 on 2025-07-11 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('therapy', '0002_auto_20250710_2340'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
