services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./.docker/postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./.docker/redis_data:/data

volumes:
  postgres_data:
    driver: local

networks:
  overlay: