# Generated by Django 5.2.4 on 2025-07-23 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('processing_successful', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audio_type', models.CharField(choices=[('recording', 'Aufnahme'), ('upload', 'Upload')], max_length=20)),
                ('file_format', models.CharField(blank=True, choices=[('mp3', 'MP3'), ('wav', 'WAV'), ('m4a', 'M4A'), ('webm', 'WebM'), ('flac', 'FLAC')], max_length=10, null=True)),
                ('audio_file', models.FileField(upload_to='audio_inputs/%Y/%m/%d/')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('transcribed_text', models.TextField(blank=True, verbose_name='Transkript')),
                ('transcription_confidence', models.FloatField(blank=True, null=True)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
                ('language', models.CharField(default='de', max_length=10)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Audio-Eingabe',
                'verbose_name_plural': 'Audio-Eingaben',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('processing_successful', models.BooleanField(default=False)),
                ('processing_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('input_type', models.CharField(choices=[('file', 'Datei-Upload'), ('text', 'Manueller Text')], max_length=20)),
                ('file_type', models.CharField(blank=True, choices=[('pdf', 'PDF'), ('word', 'Word Document'), ('txt', 'Text File'), ('manual', 'Eigener Text')], max_length=20, null=True)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='document_inputs/%Y/%m/%d/')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('extracted_text', models.TextField(verbose_name='Text-Inhalt')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Dokument-Eingabe',
                'verbose_name_plural': 'Dokument-Eingaben',
                'ordering': ['-created_at'],
            },
        ),
    ]
