# Generated by Django 5.2.4 on 2025-07-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioinput',
            name='processing_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='audioinput',
            name='processing_successful',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='documentinput',
            name='processing_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentinput',
            name='processing_successful',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
