# Generated by Django 5.2.4 on 2025-08-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_audioinput_processing_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audioinput',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio_inputs/%Y/%m/%d/'),
        ),
    ]
