# Generated by Django 5.2.4 on 2025-07-17 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTemplatePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_document_templates', models.JSONField(default=dict, help_text='Mapping von Dokumenttyp zu Template-ID', verbose_name='Standard Dokument Templates')),
                ('default_session_templates', models.JSONField(default=dict, help_text='Mapping von Sitzungstyp zu Template-ID', verbose_name='Standard Sitzungsnotizen Templates')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Benutzer Template Einstellungen',
                'verbose_name_plural': 'Benutzer Template Einstellungen',
            },
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Template Name')),
                ('description', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('template_type', models.CharField(choices=[('report', 'Reports'), ('session_notes', 'Sitzungsnotizen')], max_length=20, verbose_name='Template Typ')),
                ('system_prompt', models.TextField(blank=True, help_text='Der System-Prompt für die KI-Generierung', verbose_name='System Prompt')),
                ('user_prompt', models.TextField(help_text='Das Prompt-Template mit Platzhaltern wie {session_info}, etc.', verbose_name='User Prompt Template')),
                ('max_tokens', models.PositiveIntegerField(default=2000, verbose_name='Max Tokens')),
                ('temperature', models.FloatField(default=0.3, verbose_name='Temperature')),
                ('is_predefined', models.BooleanField(default=False, help_text='Ist dies ein vordefiniertes System-Template?', verbose_name='Vordefiniert')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktiv')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('based_on_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='document_templates.documenttemplate', verbose_name='Basiert auf Template')),
            ],
            options={
                'verbose_name': 'Dokument Template',
                'verbose_name_plural': 'Dokument Templates',
                'ordering': ['name'],
            },
        ),
    ]
