# Generated by Django 5.2.4 on 2025-07-17 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='template_type',
            field=models.CharField(choices=[('report', 'Bericht'), ('session_notes', 'Sitzungsnotiz')], max_length=20, verbose_name='Template Typ'),
        ),
    ]
