# Generated by Django 5.2.4 on 2025-07-17 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_templates', '0003_documenttemplate_user_usertemplatepreference_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertemplatepreference',
            options={'verbose_name': 'User Vorlagen Einstellung', 'verbose_name_plural': 'User Vorlagen Einstellungen'},
        ),
    ]
