# Generated by Django 5.2.4 on 2025-07-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_templates', '0004_alter_usertemplatepreference_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='general_instructions',
            field=models.TextField(default='', help_text='Allgemeine Anweisungen für den Prompt', verbose_name='General Instructions'),
            preserve_default=False,
        ),
    ]
