# Generated by Django 5.2.4 on 2025-07-17 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="sessions",
        ),
        migrations.AlterField(
            model_name="report",
            name="content",
            field=models.TextField(blank=True, verbose_name="Inhalt"),
        ),
        migrations.CreateModel(
            name="ReportContextFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("file_name", models.CharField(max_length=255, verbose_name="Dateiname")),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("word", "Word Document"),
                            ("txt", "Text File"),
                            ("manual", "Manueller Text Input"),
                        ],
                        max_length=20,
                        verbose_name="Dateityp",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Dateigröße (Bytes)"
                    ),
                ),
                (
                    "original_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="report_context/%Y/%m/%d/",
                        verbose_name="Originaldatei",
                    ),
                ),
                ("extracted_text", models.TextField(verbose_name="Extrahierter Text")),
                (
                    "extraction_successful",
                    models.BooleanField(default=False, verbose_name="Extraktion erfolgreich"),
                ),
                (
                    "extraction_error",
                    models.TextField(blank=True, verbose_name="Extraktionsfehler"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Erstellt am")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Aktualisiert am")),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="context_files",
                        to="reports.report",
                        verbose_name="Bericht",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kontext-Datei",
                "verbose_name_plural": "Kontext-Dateien",
                "ordering": ["-created_at"],
            },
        ),
    ]
