# Generated by Django 5.2.4 on 2025-07-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_report_sessions_alter_report_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcontextfile',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('word', 'Word Document'), ('txt', 'Text File'), ('manual', 'Eigener Text')], max_length=20, verbose_name='Dateityp'),
        ),
    ]
