# Generated by Django 5.2.4 on 2025-07-14 11:31

from django.db import migrations


def create_predefined_document_templates(apps, schema_editor):
    """Create predefined document templates from existing prompts"""
    DocumentTemplate = apps.get_model('documents', 'DocumentTemplate')
    
    # Import the existing prompts
    from reports.prompts import DOCUMENT_PROMPTS, REPORT_SYSTEM_PROMPT
    
    for doc_type, template_data in DOCUMENT_PROMPTS.items():
        DocumentTemplate.objects.create(
            name=template_data['name'],
            description=f"Vordefiniertes Template für {template_data['name']}",
            template_type='document',
            document_type=doc_type,
            system_prompt=REPORT_SYSTEM_PROMPT,
            user_prompt=template_data['prompt'],
            max_tokens=2000,
            temperature=0.3,
            is_predefined=True,
            is_active=True
        )


def create_predefined_session_templates(apps, schema_editor):
    """Create predefined session notes templates from existing prompts"""
    DocumentTemplate = apps.get_model('documents', 'DocumentTemplate')
    
    # Import the existing session notes prompts
    from sessions.prompts import SESSION_NOTES_TEMPLATES, SYSTEM_PROMPT
    
    for session_type, template_data in SESSION_NOTES_TEMPLATES.items():
        DocumentTemplate.objects.create(
            name=template_data['name'],
            description=f"Vordefiniertes Template für {template_data['name']}",
            template_type='session_notes',
            system_prompt=SYSTEM_PROMPT,
            user_prompt=template_data['prompt'],
            max_tokens=1000,
            temperature=0.3,
            is_predefined=True,
            is_active=True
        )


def reverse_create_templates(apps, schema_editor):
    """Remove predefined templates"""
    DocumentTemplate = apps.get_model('documents', 'DocumentTemplate')
    DocumentTemplate.objects.filter(is_predefined=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_usertemplatepreference_documenttemplate'),
    ]

    operations = [
        migrations.RunPython(
            create_predefined_document_templates,
            reverse_create_templates
        ),
        migrations.RunPython(
            create_predefined_session_templates,
            reverse_create_templates
        ),
    ]
