# Generated by Django 5.2.4 on 2025-07-14 11:38

from django.db import migrations


def update_document_templates(apps, schema_editor):
    """Update document templates to remove context variables"""
    DocumentTemplate = apps.get_model('documents', 'DocumentTemplate')
    
    # Define the cleaned templates (structure only, no context variables)
    template_updates = {
        'Abschlussbericht': """**ABSCHLUSSBERICHT**

<p><strong>1. EINLEITUNG</strong></p>
<ul>
<li>Kurze Darstellung der Ausgangssituation</li>
<li>Anlass der Therapie</li>
</ul>

<p><strong>2. DIAGNOSTISCHE EINSCHÄTZUNG</strong></p>
<ul>
<li>Hauptdiagnose</li>
<li>Differentialdiagnosen</li>
<li>Psychosoziale Faktoren</li>
</ul>

<p><strong>3. THERAPIEVERLAUF</strong></p>
<ul>
<li>Wichtige Stationen der Therapie</li>
<li>Bearbeitete Themen</li>
<li>Krisen und deren Bewältigung</li>
</ul>

<p><strong>4. ERREICHTE ZIELE</strong></p>
<ul>
<li>Positive Veränderungen</li>
<li>Erreichte Therapieziele</li>
<li>Neue Bewältigungsstrategien</li>
</ul>

<p><strong>5. AKTUELLER STATUS</strong></p>
<ul>
<li>Aktuelle Symptomatik</li>
<li>Psychosoziale Situation</li>
<li>Bewältigungsfähigkeiten</li>
</ul>

<p><strong>6. PROGNOSE UND EMPFEHLUNGEN</strong></p>
<ul>
<li>Einschätzung der weiteren Entwicklung</li>
<li>Empfehlungen für die Zukunft</li>
<li>Nachsorgeplan</li>
</ul>

<p><strong>7. ABSCHLUSS</strong></p>
<ul>
<li>Zusammenfassung der Therapie</li>
<li>Dank an den Patienten für die Zusammenarbeit</li>
</ul>

Der Bericht sollte professionell, strukturiert und für medizinische Zwecke geeignet sein.""",

        'Verlaufsbericht': """**VERLAUFSBERICHT**

<p><strong>1. AKTUELLE SITUATION</strong></p>
<ul>
<li>Aktuelle Beschwerden und Symptome</li>
<li>Psychosoziale Situation</li>
<li>Belastungsfaktoren</li>
</ul>

<p><strong>2. THERAPIEVERLAUF BISLANG</strong></p>
<ul>
<li>Wichtige Stationen der Therapie</li>
<li>Bearbeitete Themen</li>
<li>Erreichte Fortschritte</li>
</ul>

<p><strong>3. AKTUELLE SITZUNGEN</strong></p>
<ul>
<li>Fokus der letzten Sitzungen</li>
<li>Neue Erkenntnisse</li>
<li>Schwierigkeiten und Rückschläge</li>
</ul>

<p><strong>4. FORTSCHRITT UND VERÄNDERUNGEN</strong></p>
<ul>
<li>Positive Entwicklungen</li>
<li>Verbleibende Herausforderungen</li>
<li>Neue Bewältigungsstrategien</li>
</ul>

<p><strong>5. NÄCHSTE SCHRITTE</strong></p>
<ul>
<li>Geplante Interventionen</li>
<li>Fokus für kommende Sitzungen</li>
<li>Ziele für die nächste Phase</li>
</ul>

<p><strong>6. PROGNOSE</strong></p>
<ul>
<li>Einschätzung der weiteren Entwicklung</li>
<li>Erwartete Dauer der Therapie</li>
</ul>

Der Bericht sollte den aktuellen Stand der Therapie widerspiegeln und für die weitere Behandlung relevant sein.""",

        'Befundbericht': """**BEFUNDBERICHT**

<p><strong>1. ANAMNESE</strong></p>
<ul>
<li>Aktuelle Beschwerden</li>
<li>Psychiatrische Vorgeschichte</li>
<li>Somatische Vorgeschichte</li>
<li>Familienanamnese</li>
<li>Sozialanamnese</li>
</ul>

<p><strong>2. PSYCHISCHER BEFUND</strong></p>
<ul>
<li>Bewusstsein und Orientierung</li>
<li>Stimmung und Affekt</li>
<li>Denken und Wahrnehmung</li>
<li>Antrieb und Psychomotorik</li>
<li>Kognitive Funktionen</li>
</ul>

<p><strong>3. DIAGNOSTISCHE EINSCHÄTZUNG</strong></p>
<ul>
<li>Hauptdiagnose nach ICD-10</li>
<li>Differentialdiagnosen</li>
<li>Schweregrad</li>
<li>Psychosoziale Faktoren</li>
</ul>

<p><strong>4. THERAPIEEMPFEHLUNG</strong></p>
<ul>
<li>Indikation für Psychotherapie</li>
<li>Empfohlene Therapieform</li>
<li>Therapieziele</li>
<li>Erwartete Dauer</li>
</ul>

<p><strong>5. PROGNOSE</strong></p>
<ul>
<li>Einschätzung der Behandelbarkeit</li>
<li>Erwartete Entwicklung</li>
<li>Risikofaktoren</li>
</ul>

Der Befundbericht sollte medizinisch fundiert und für weitere Behandler verständlich sein.""",

        'Indikationsstellung': """**INDIKATIONSSTELLUNG**

<p><strong>1. AKTUELLE PROBLEMATIK</strong></p>
<ul>
<li>Hauptbeschwerden</li>
<li>Symptomatik</li>
<li>Leidensdruck</li>
<li>Funktionsbeeinträchtigung</li>
</ul>

<p><strong>2. DIAGNOSTISCHE EINSCHÄTZUNG</strong></p>
<ul>
<li>Verdachtsdiagnose</li>
<li>Differentialdiagnosen</li>
<li>Komorbiditäten</li>
<li>Psychosoziale Faktoren</li>
</ul>

<p><strong>3. INDIKATION FÜR PSYCHOTHERAPIE</strong></p>
<ul>
<li>Begründung der Indikation</li>
<li>Ausschlusskriterien</li>
<li>Kontraindikationen</li>
<li>Risiko-Nutzen-Abwägung</li>
</ul>

<p><strong>4. THERAPIEEMPFEHLUNG</strong></p>
<ul>
<li>Empfohlene Therapieform</li>
<li>Begründung der Wahl</li>
<li>Alternative Behandlungsoptionen</li>
<li>Setting-Empfehlung</li>
</ul>

<p><strong>5. THERAPIEZIELE</strong></p>
<ul>
<li>Primäre Ziele</li>
<li>Sekundäre Ziele</li>
<li>Realistische Erwartungen</li>
<li>Erfolgskriterien</li>
</ul>

<p><strong>6. PROGNOSE</strong></p>
<ul>
<li>Behandelbarkeit</li>
<li>Erwartete Dauer</li>
<li>Erfolgsaussichten</li>
<li>Risikofaktoren</li>
</ul>

Die Indikationsstellung sollte medizinisch begründet und für Kostenträger nachvollziehbar sein.""",

        'Anamnese': """**ANAMNESE**

<p><strong>1. AKTUELLE BESCHWERDEN</strong></p>
<ul>
<li>Hauptbeschwerden</li>
<li>Beginn und Verlauf</li>
<li>Auslöser und aufrechterhaltende Faktoren</li>
<li>Schweregrad und Beeinträchtigung</li>
</ul>

<p><strong>2. PSYCHIATRISCHE VORGESCHICHTE</strong></p>
<ul>
<li>Frühere psychische Erkrankungen</li>
<li>Vorbehandlungen</li>
<li>Medikamentöse Behandlungen</li>
<li>Stationäre Aufenthalte</li>
</ul>

<p><strong>3. SOMATISCHE VORGESCHICHTE</strong></p>
<ul>
<li>Relevante körperliche Erkrankungen</li>
<li>Operationen</li>
<li>Medikamente</li>
<li>Allergien</li>
</ul>

<p><strong>4. FAMILIENANAMNESE</strong></p>
<ul>
<li>Psychische Erkrankungen in der Familie</li>
<li>Genetische Belastungen</li>
<li>Familiäre Konflikte</li>
<li>Unterstützende Faktoren</li>
</ul>

<p><strong>5. SOZIALANAMNESE</strong></p>
<ul>
<li>Familienverhältnisse</li>
<li>Partnerschaft</li>
<li>Berufliche Situation</li>
<li>Soziale Kontakte</li>
<li>Finanzielle Situation</li>
</ul>

<p><strong>6. ENTWICKLUNGSANAMNESE</strong></p>
<ul>
<li>Schwangerschaft und Geburt</li>
<li>Frühe Entwicklung</li>
<li>Schulische Entwicklung</li>
<li>Berufliche Entwicklung</li>
<li>Lebenskrisen</li>
</ul>

<p><strong>7. PERSÖNLICHKEITSANAMNESE</strong></p>
<ul>
<li>Charaktereigenschaften</li>
<li>Bewältigungsstrategien</li>
<li>Stärken und Ressourcen</li>
<li>Schwächen und Vulnerabilitäten</li>
</ul>

Die Anamnese sollte umfassend und für die Therapieplanung relevant sein.""",

        'Diagnose': """**DIAGNOSE**

<p><strong>1. HAUPTDIAGNOSE</strong></p>
<ul>
<li>ICD-10 Diagnose</li>
<li>Schweregrad</li>
<li>Verlaufstyp</li>
<li>Begründung der Diagnose</li>
</ul>

<p><strong>2. DIFFERENTIALDIAGNOSEN</strong></p>
<ul>
<li>Abzugrenzende Störungen</li>
<li>Ausschlusskriterien</li>
<li>Komorbiditäten</li>
<li>Differentialdiagnostische Überlegungen</li>
</ul>

<p><strong>3. PSYCHOSOZIALE FAKTOREN</strong></p>
<ul>
<li>Belastende Lebensereignisse</li>
<li>Aktuelle Belastungen</li>
<li>Soziale Unterstützung</li>
<li>Bewältigungsressourcen</li>
</ul>

<p><strong>4. FUNKTIONSBEEINTRÄCHTIGUNG</strong></p>
<ul>
<li>Berufliche Beeinträchtigung</li>
<li>Soziale Beeinträchtigung</li>
<li>Familiäre Beeinträchtigung</li>
<li>Grad der Beeinträchtigung</li>
</ul>

<p><strong>5. RISIKOFAKTOREN</strong></p>
<ul>
<li>Suizidalität</li>
<li>Selbstgefährdung</li>
<li>Fremdgefährdung</li>
<li>Suchtgefährdung</li>
</ul>

<p><strong>6. PROTECTIVE FAKTOREN</strong></p>
<ul>
<li>Soziale Unterstützung</li>
<li>Bewältigungsstrategien</li>
<li>Motivation zur Behandlung</li>
<li>Ressourcen</li>
</ul>

Die Diagnose sollte fundiert und für die Therapieplanung relevant sein.""",

        'Therapieplan': """**THERAPIEPLAN**

<p><strong>1. DIAGNOSE UND INDIKATION</strong></p>
<ul>
<li>Hauptdiagnose</li>
<li>Indikation für Psychotherapie</li>
<li>Ausschlusskriterien</li>
<li>Kontraindikationen</li>
</ul>

<p><strong>2. THERAPIEZIELE</strong></p>
<ul>
<li>Primäre Ziele</li>
<li>Sekundäre Ziele</li>
<li>Kurzzeitziele</li>
<li>Langzeitziele</li>
<li>Erfolgskriterien</li>
</ul>

<p><strong>3. THERAPIEMETHODE</strong></p>
<ul>
<li>Gewählte Therapieform</li>
<li>Begründung der Wahl</li>
<li>Spezifische Techniken</li>
<li>Anpassungen an den Patienten</li>
</ul>

<p><strong>4. THERAPIEVERLAUF</strong></p>
<ul>
<li>Phase 1: Aufbau und Stabilisierung</li>
<li>Phase 2: Bearbeitung der Probleme</li>
<li>Phase 3: Konsolidierung und Abschluss</li>
<li>Übergänge zwischen Phasen</li>
</ul>

<p><strong>5. INTERVENTIONEN</strong></p>
<ul>
<li>Spezifische Interventionen</li>
<li>Hausaufgaben und Übungen</li>
<li>Kriseninterventionen</li>
<li>Rückfallprophylaxe</li>
</ul>

<p><strong>6. EVALUATION</strong></p>
<ul>
<li>Erfolgskontrolle</li>
<li>Messinstrumente</li>
<li>Zeitpunkte der Evaluation</li>
<li>Anpassung des Plans</li>
</ul>

<p><strong>7. ABSCHLUSSKRITERIEN</strong></p>
<ul>
<li>Kriterien für Therapieende</li>
<li>Nachsorgeplan</li>
<li>Rückfallprophylaxe</li>
<li>Wiedereinstiegskriterien</li>
</ul>

Der Therapieplan sollte strukturiert und für die Behandlung leitend sein.""",

        'Brief': """**BRIEF**

<p><strong>1. ANREDE UND EINLEITUNG</strong></p>
<ul>
<li>Professionelle Anrede</li>
<li>Bezug auf vorherige Kontakte</li>
<li>Anlass des Briefes</li>
</ul>

<p><strong>2. AKTUELLE SITUATION</strong></p>
<ul>
<li>Zusammenfassung der aktuellen Situation</li>
<li>Wichtige Entwicklungen</li>
<li>Aktuelle Beschwerden</li>
</ul>

<p><strong>3. THERAPIEVERLAUF</strong></p>
<ul>
<li>Wichtige Stationen der Behandlung</li>
<li>Erreichte Fortschritte</li>
<li>Verbleibende Herausforderungen</li>
</ul>

<p><strong>4. EMPFEHLUNGEN</strong></p>
<ul>
<li>Konkrete Empfehlungen</li>
<li>Weitere Schritte</li>
<li>Kooperation mit anderen Behandlern</li>
</ul>

<p><strong>5. ABSCHLUSS</strong></p>
<ul>
<li>Zusammenfassung</li>
<li>Dank und Wertschätzung</li>
<li>Professionelle Grußformel</li>
</ul>

Der Brief sollte professionell, respektvoll und für den Empfänger verständlich sein.""",

        'Sonstiges': """**DOKUMENT**

Erstelle ein strukturiertes, professionelles Dokument, das die wichtigsten Informationen zur Behandlung zusammenfasst. Das Dokument sollte enthalten:

<p><strong>1. PATIENTENINFORMATIONEN</strong></p>
<ul>
<li>Relevante biografische Daten</li>
<li>Aktuelle Situation</li>
</ul>

<p><strong>2. THERAPIEINFORMATIONEN</strong></p>
<ul>
<li>Therapieverlauf</li>
<li>Wichtige Entwicklungen</li>
<li>Erreichte Fortschritte</li>
</ul>

<p><strong>3. FAZIT UND EMPFEHLUNGEN</strong></p>
<ul>
<li>Zusammenfassung</li>
<li>Empfehlungen für die Zukunft</li>
</ul>

Das Dokument sollte professionell und für medizinische Zwecke geeignet sein.""",
    }
    
    # Update document templates
    for name, new_prompt in template_updates.items():
        try:
            template = DocumentTemplate.objects.get(name=name, template_type='document')
            template.user_prompt = new_prompt
            template.system_prompt = ''  # Clear system prompt as it's now hardcoded
            template.save()
        except DocumentTemplate.DoesNotExist:
            print(f"Template {name} not found")


def update_session_templates(apps, schema_editor):
    """Update session notes templates to remove context variables"""
    DocumentTemplate = apps.get_model('documents', 'DocumentTemplate')
    
    session_template_updates = {
        'Erstgespräch': """**SITZUNGSNOTIZEN - ERSTGESPRÄCH**

<p><strong>ANAMNESE</strong></p>
<ul>
<li>Aktuelle Beschwerden und Symptome</li>
<li>Psychosoziale Situation</li>
<li>Biografische Informationen</li>
<li>Vorbehandlungen</li>
</ul>

<p><strong>DIAGNOSTISCHE EINSCHÄTZUNG</strong></p>
<ul>
<li>Erste Eindrücke</li>
<li>Mögliche Diagnosen</li>
<li>Risikofaktoren</li>
</ul>

<p><strong>THERAPIEZIELE</strong></p>
<ul>
<li>Hauptziele des Patienten</li>
<li>Behandlungsansatz</li>
</ul>

<p><strong>NÄCHSTE SCHRITTE</strong></p>
<ul>
<li>Empfohlene Maßnahmen</li>
<li>Terminvereinbarung</li>
</ul>""",

        'Verlaufsgespräch': """**SITZUNGSNOTIZEN - VERLAUFSGESPRÄCH**

<p><strong>VERLAUF SEIT LETZTER SITZUNG</strong></p>
<ul>
<li>Veränderungen und Fortschritte</li>
<li>Schwierigkeiten und Rückschläge</li>
<li>Compliance mit Übungen/Aufgaben</li>
</ul>

<p><strong>AKTUELLE SITZUNG</strong></p>
<ul>
<li>Hauptthemen und Inhalte</li>
<li>Neue Erkenntnisse</li>
<li>Bearbeitete Problembereiche</li>
</ul>

<p><strong>FORTSCHRITT UND VERÄNDERUNGEN</strong></p>
<ul>
<li>Positive Entwicklungen</li>
<li>Verbleibende Herausforderungen</li>
<li>Erreichte Ziele</li>
</ul>

<p><strong>NÄCHSTE SCHRITTE</strong></p>
<ul>
<li>Neue Aufgaben/Übungen</li>
<li>Fokus für nächste Sitzung</li>
<li>Terminvereinbarung</li>
</ul>""",

        'Abschlussgespräch': """**SITZUNGSNOTIZEN - ABSCHLUSSGESPRÄCH**

<p><strong>THERAPIEFORTSCHRITT</strong></p>
<ul>
<li>Erreichte Ziele</li>
<li>Positive Veränderungen</li>
<li>Gelernte Strategien</li>
</ul>

<p><strong>AKTUELLER STATUS</strong></p>
<ul>
<li>Aktuelle Symptomatik</li>
<li>Bewältigungsfähigkeiten</li>
<li>Psychosoziale Situation</li>
</ul>

<p><strong>RÜCKFALLPROPHYLAXE</strong></p>
<ul>
<li>Risikofaktoren</li>
<li>Frühwarnzeichen</li>
<li>Bewältigungsstrategien</li>
</ul>

<p><strong>ABSCHLUSS</strong></p>
<ul>
<li>Zusammenfassung der Therapie</li>
<li>Empfehlungen für die Zukunft</li>
<li>Nachsorgeplan</li>
</ul>""",
    }
    
    # Update session notes templates
    for name, new_prompt in session_template_updates.items():
        try:
            template = DocumentTemplate.objects.get(name=name, template_type='session_notes')
            template.user_prompt = new_prompt
            template.system_prompt = ''  # Clear system prompt as it's now hardcoded
            template.save()
        except DocumentTemplate.DoesNotExist:
            print(f"Session template {name} not found")


def reverse_update_templates(apps, schema_editor):
    """Reverse the template updates"""
    # This would restore the original prompts, but for simplicity we'll just pass
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20250714_1331'),
    ]

    operations = [
        migrations.RunPython(
            update_document_templates,
            reverse_update_templates
        ),
        migrations.RunPython(
            update_session_templates,
            reverse_update_templates
        ),
    ]
