# Generated by Django 5.2.4 on 2025-07-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20250714_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='documenttemplate',
            name='document_type',
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='template_type',
            field=models.CharField(choices=[('document', 'Dokumente'), ('session_notes', 'Sitzungsnotizen')], max_length=20, verbose_name='Template Typ'),
        ),
    ]
