# Generated by Django 5.2.4 on 2025-07-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_report_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Zusammenfassung'),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Titel'),
        ),
    ]
