# Generated by Django 5.2.4 on 2025-07-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_report_summary_alter_report_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_exported',
            field=models.BooleanField(default=False, help_text='Gibt an, ob das Dokument bereits als Datei exportiert wurde', verbose_name='Exportiert'),
        ),
        migrations.DeleteModel(
            name='ReportContextFile',
        ),
    ]
