# Generated by Django 5.2.4 on 2025-07-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_report_is_exported_delete_reportcontextfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='is_generating',
            field=models.BooleanField(default=False),
        ),
    ]
