# Generated by Django 5.2.4 on 2025-07-11 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('therapy', '0003_delete_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titel')),
                ('content', models.TextField(verbose_name='Inhalt')),
                ('document_type', models.CharField(choices=[('abschlussbericht', 'Abschlussbericht'), ('verlaufsbericht', 'Verlaufsbericht'), ('befundbericht', 'Befundbericht'), ('indikationsstellung', 'Indikationsstellung'), ('anamnese', 'Anamnese'), ('diagnose', 'Diagnose'), ('therapieplan', 'Therapieplan'), ('brief', 'Brief'), ('other', 'Sonstiges')], default='abschlussbericht', max_length=20, verbose_name='Dokumenttyp')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
                ('sessions', models.ManyToManyField(blank=True, to='therapy.session', verbose_name='Zugehörige Sitzungen')),
                ('therapy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therapy.therapy', verbose_name='Therapie')),
            ],
            options={
                'verbose_name': 'Dokument',
                'verbose_name_plural': 'Dokumente',
                'ordering': ['-created_at'],
            },
        ),
    ]
