# Generated by Django 5.2.4 on 2025-07-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_sessions', '0002_session_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='patient_gender',
            field=models.CharField(choices=[('male', 'Männlich'), ('female', 'Weiblich'), ('diverse', 'Divers'), ('not_specified', 'Nicht angegeben')], default='not_specified', help_text='Geschlecht des Patienten für geschlechtsspezifische KI-Generierung', max_length=20, verbose_name='Geschlecht des Patienten'),
        ),
    ]
