# Generated by Django 5.2.4 on 2025-07-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_sessions', '0003_session_patient_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='notes',
        ),
        migrations.AddField(
            model_name='session',
            name='content',
            field=models.TextField(blank=True, verbose_name='Inhalt'),
        ),
    ]
