# Generated by Django 5.2.4 on 2025-07-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_sessions', '0004_remove_session_notes_session_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiorecording',
            name='session',
        ),
        migrations.RemoveField(
            model_name='transcription',
            name='recording',
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
        migrations.AddField(
            model_name='session',
            name='is_exported',
            field=models.BooleanField(default=False, help_text='Gibt an, ob das Dokument bereits als Datei exportiert wurde', verbose_name='Exportiert'),
        ),
        migrations.DeleteModel(
            name='AudioRecording',
        ),
        migrations.DeleteModel(
            name='Transcription',
        ),
    ]
