# Generated by Django 5.2.4 on 2025-07-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_sessions', '0005_remove_audiorecording_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='is_generating',
            field=models.BooleanField(default=False),
        ),
    ]
