# Generated by Django 5.2.4 on 2025-07-10 19:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Vorname')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nachname')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Geburtsdatum')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-Mail')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adresse')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notizen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Erstellt am')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualisiert am')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patienten',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript_ttl_hours', models.PositiveIntegerField(default=24, help_text='Nach wie vielen Stunden werden Transkripte automatisch gelöscht?', verbose_name='Transkript-Aufbewahrungszeit (Stunden)')),
                ('openai_api_key', models.CharField(blank=True, help_text='API Key für OpenAI Whisper und GPT', max_length=255, verbose_name='OpenAI API Key')),
                ('max_audio_duration_minutes', models.PositiveIntegerField(default=60, help_text='Maximale Länge für Audio-Aufnahmen', verbose_name='Maximale Audio-Dauer (Minuten)')),
                ('auto_transcribe', models.BooleanField(default=True, help_text='Sollen Audio-Aufnahmen automatisch transkribiert werden?', verbose_name='Automatische Transkription')),
                ('auto_summarize', models.BooleanField(default=True, help_text='Sollen Transkripte automatisch zusammengefasst werden?', verbose_name='Automatische Zusammenfassung')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Einstellungen',
                'verbose_name_plural': 'Einstellungen',
            },
        ),
    ]
